spring:
  profiles:
    active:
    - dev

---
spring:
  profiles: dev
  application: 
    name: microservicecloud-config-mical-dev
    
---
spring:
  profiles: test
  application: 
    name: microservicecloud-config-mical-test